
default: &default
  adapter: postgresql
  pool: 5 # Specifies the maximum number of connections that can be opened
  timeout: 5000 # in milliseconds. This is how long the app will wait for a database response
  encoding: unicode
  username: obli
  password: obli

development:
  <<: *default # inherits from default
  database: main_development

test:
  <<: *default
  database: main_test

production:
  <<: *default
  database: main



